### ISSUE TITLE
Error 0xc0000007b

### ISSUE THREAD

**Issue by ghost** [ih1115/CheatRite#13]
Few users have experienced an issue where this error message pops up. There's a possible fix, I can't confirm this works because I haven't encountered the problem, but it's worth a try.

1) Download this: https://drive.google.com/file/d/0B0h-NHKRYdb3cHRDQzlXMzNpNGc/view
2) Extract it somewhere, open the folder, open the svcpack folder and run aio-runtimes.exe
3) Install all runtimes
4) Reboot PC
5) Try open the program

**Comment by SrMths** [comment]
Did not work

**Comment by escitue** [comment]
I'll look for another solution

**Comment by escitue** [comment]
Possible fix 2: https://github.com/ih1115/CheatRite/releases/tag/1.1b
