### ISSUE TITLE
Champion list offset

### ISSUE THREAD

**Issue by rafaelcarpeta** [ih1115/CheatRite#19]
the new champion list offset is pointing to nothing, even on cheat engine

**Comment by ih1115** [comment]
Don't have much time on my hands but you could try these offsets

https://github.com/ih1115/CheatRite/blob/champion_list/Core/headers/Offsets.hpp

**Comment by rafaelcarpeta** [comment]
I found a working Champion lista, vir o Luke to know How did you found the local player x, y
