### ISSUE TITLE
Why do u excluded everything?

### ISSUE THREAD

**Issue by tAgKilL** [ih1115/CheatRite#22]
The Discord and de site don't exists anymore

**Comment by ih1115** [comment]
I didn't run/own the discord or site nor did I ever try to sell anything.

**Comment by tAgKilL** [comment]
Someone try to scam us

**Comment by tAgKilL** [comment]
The cheatrite 'll be updated?

**Comment by ih1115** [comment]
I have exams this week.
I could update this next week if people still want it.
Otherwise no since I don't play the game.

**Comment by tAgKilL** [comment]
Why do u not selling this?

Make a private cheat about Battlerite and get rich, many people 'll pay for

**Comment by ih1115** [comment]
No

**Comment by rafaelcarpeta** [comment]
you now pretending that you dind know nothing, the link to discord is on your git, grow some balls

**Comment by ih1115** [comment]
@rafaelcarpeta 
Bro it started off as a support discord that he made and initially I had permissions to anything on.
He later changed it to his own stuff with his own site and started trying to sell his own stuff which he made clear in his announcements and removed any permissions which I didn't really care about anyway.

Anything that was trying to be sold is not related to me.

**Comment by rafaelcarpeta** [comment]
my apologies them, didnt know that was you ttap, my bad
