### ISSUE TITLE
Why do u excluded the Discord Group?

### ISSUE THREAD

**Issue by tAgKilL** [ih1115/CheatRite#25]
A lot of Brazzilians come to me to understand why do you excluded the Discord Group, can u anwser me pls?

**Comment by rafaelcarpeta** [comment]
https://discord.gg/Jux2mm


2018-01-21 6:48 GMT-02:00 tAgKilL <notifications@github.com>:

**Comment by rafaelcarpeta** [comment]
Tag se tiver contato da bele pede pra ele entrar nesse discord que te passei


2018-01-21 12:35 GMT-02:00 Rafael.Carpeta <rafael.carpeta@gmail.com>:

**Comment by rafaelcarpeta** [comment]
Discord baniu nosso servidor a pedido da stunlock


2018-01-21 12:36 GMT-02:00 Rafael.Carpeta <rafael.carpeta@gmail.com>:

**Comment by vittbol** [comment]
Belle aqui, id do discord para me adicionar é BLL#3287

**Comment by rafaelcarpeta** [comment]
new discor guys https://discord.gg/bGMmZay

**Comment by Xknights** [comment]
discord banned again

**Comment by ih1115** [comment]
Yep....
