### ISSUE TITLE
Discord group deleted again?

### ISSUE THREAD

**Issue by allex707** [ih1115/CheatRite#26]
What happened? taken down or wiped project?

**Comment by ih1115** [comment]
This time my account and the server got deleted because it was reported and is against discord ToS to have any discord related to cheating.

**Comment by ih1115** [comment]
Oh you mean the latest take down.
I only just realised, I think it would be along the same lines though..
Discord is just not the way forward for the dev team

**Comment by allex707** [comment]
Soo, any better way of communication?

**Comment by PredatOx** [comment]
please update the cheat

**Comment by plsfixrito** [comment]
The project is still at work, for now we will use our forum for communication https://www.battleright.net/forum/
